import type { Metadata } from "next";
import { Mandali, Rokkitt } from "next/font/google";
import "./globals.css";
import { MenuBar } from "./components/menu/MenuBar";


const mandali = Mandali({
  variable: "--font-mandali",
  subsets: ["latin"],
  weight: "400",
});

const rokkitt = Rokkitt({
  variable: "--font-rokkitt",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Charlotte Jacques",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${mandali.variable} ${rokkitt.variable} antialiased`}>
        <MenuBar/>
        <div className='m-8 lg:m-24'>{children}</div>
      </body>
    </html>
  );
}
